### ISSUE TITLE
enter need to be added

### ISSUE THREAD

**Issue by ImaginistEngineer** [scaryken/SongFormatter#2]
输入之后字符处理可以换行，计算输入字符数，按照字数进行换行输出，形成松的回车格式

**Comment by scaryken** [comment]
已经做了常见标点符号替换为换行了捏，如下图。
如果要实现一句话内的换行，为了效果需要做自然语言识别，就比较费事了
![image](https://user-images.githubusercontent.com/15189769/162352335-5abd9f3a-f149-45a4-a1a9-e6f3f377612b.png)
